### ISSUE TITLE
[short-term] test massive portal 

### ISSUE THREAD

**Issue by tyesamson** [tyesamson/the-finishing-suite#48]
i’ll DM you the password to get past the first frame.

have had clients say that in it’s current form (ie pre-your cms’d version) that once they enter the password and upload files, the “upload” button is cropped out below the bottom of the frame

**Comment by mattdwen** [comment]
You're a little bit screwed here, because it's an iframe, and you don't have control of what's in it, you get to pick one size and that's it.

I've made it bigger so that it fits once you're signed in, and seems to work on my devices here, but you get a bit more white space around the login screen.

The alternatives are I can turn on scroll bars inside the iframe (which looks ugly), or don't use an iframe and link off the site.

I've think what I've done works.
