### ISSUE TITLE
hamburger menu doesnt work on mobile

### ISSUE THREAD

**Issue by tyesamson** [tyesamson/the-finishing-suite#67]

**Comment by mattdwen** [comment]
Your phone, or something else?
It's working on mine atm.

**Comment by tyesamson** [comment]
on my phone and on someone elses, the menu doesnt work for about 20 seconds or so, then suddenly its like the page catches up and goes to all the sections i clicked while waiting all at once

**Comment by mattdwen** [comment]
I think it's because the images don't load until you scroll to them, and didn't have fixed height set to them, so as you click a menu and scroll past the images the page gets longer, and the place you want to be is now X pixels more further down the page.

Give this a publish and see if it's any better.

**Comment by tyesamson** [comment]
did you push to develop?

**Comment by tyesamson** [comment]
sorry found it heh
